### ISSUE TITLE
Using Prometheus remote_write with push gateway

### ISSUE THREAD

**Issue by boynux** [prometheus/pushgateway#110]
I want to transfer metrics from one prometheus to another one using push gateway. I setup a push gateway instance and configured prometheus [remote_write](https://prometheus.io/docs/operating/configuration/#<remote_write>) to send metrics to push gateway. And another prometheus instance to scrape the metrics from the push gateway.

The issue is that prometheus is not able to send data to push gateway and gets 500 error.
I could not find the issue and there are not much information for this setup. Any help will be appreciated.

Prometheus config:

```
global:
  # Scrape the targets for metrics every 15 seconds.
  scrape_interval: 15s
scrape_configs:
# Define our etcd cluster as a monitoring job.
- job_name: 'etcd'
  static_configs:
  - targets:
    - 127.0.0.1:2379

remote_write:
  url: http://localhost:9091/metrics/job/test1
```

Prometheus error while pushing data:

```
WARN[8628] error sending 25 samples to remote storage: server returned HTTP status 500 Internal Server Error  source=queue_manager.go:246
```

There is not logs at push gateway side. But push gateway works with simple `curl` commnand like: 

```
echo -e "some_metric 3.14" | curl --data-binary @- http://localhost:9091/metrics/job/some_job
```
