### ISSUE TITLE
Unable to expose through istio ingress gateway

### ISSUE THREAD

**Issue by lyonsaj** [prometheus/pushgateway#342]
I am unable to expose the pushgateway through istio ingress gateway. I have tried to expose through a the path ```/pushgateway``` and through a sub domain.. 

helm install is 
```
helm install prometheus-pushgateway \
  --set ingress.enabled=true  \
  --set ingress.hosts[0]="loadbalancer.dns.com" \
  --set ingress.path="/pushgateway" \
  --set serviceMonitor.namespace=istio-system stable/prometheus-pushgateway -n istio-system
```

or remove ```ingress.path``` or add ```pushgateway.``` to the host to try for the subdomain. 

I have found that the ingress.path isnt recognized by istio, so I can hit the pushgateway by adding a rewrite to my virtual service like this
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-pushgateway
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        prefix: /pushgateway
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9091
        host: prometheus-pushgateway.istio-system.svc.cluster.local
```

The problem now is that I am unable to get to the ```/static``` path or anything else that I may need. 

I have to be doing this wrong. Can anyone offer advice?
