### ISSUE TITLE
tls_server_config/min_version seems to do nothing for the Push Gateway

### ISSUE THREAD

**Issue by rlees85** [prometheus/pushgateway#659]
## Bug Report
**What did you do?**

I am using a web config configuration file, something like:
```
tls_server_config:
  key_file: /key.pem
  cert_file: /cert.pem
  min_version: "TLS13"
```

**What did you expect to see?**
TLSv1.2 connections being denied

**What did you see instead? Under which circumstances?**
A Go client successfully connects using TLSv1.2 (according to Wireshark). When forcing Go to use TLSv1.3 a TLSv1.3 connection is used.

**Environment**
archlinux

* Pushgateway version:

		1.9.0

* Pushgateway command line:

		`--web.config.file=/web.yml`

It looks like all Prometheus things use the same core for web stuff. I am wondering if the push gateway has not been updated recently (with this component)?
