### ISSUE TITLE
Doubling the data

### ISSUE THREAD

**Issue by polRk** [prometheus/pushgateway#711]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
Now, in my grafana I see labels twice:

<img width="278" alt="image" src="https://github.com/user-attachments/assets/f6000953-100b-4761-a7ba-04448ca15f76" />

**What did you expect to see?**
Only one single unique label

**What did you see instead? Under which circumstances?**

**Environment**
```yaml
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "10000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
    volumes:
      - prometheus_data:/prometheus
      - ./extras/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
    volumes:
      - pushgateway_data:/data

volumes:
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
  pushgateway_data:
    driver: local
```

```yaml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

```
* System information:

		Insert output of `uname -srm` here.

* Pushgateway version:

		Insert output of `pushgateway --version` here.

* Pushgateway command line:

		Insert full command line.

* Logs:
```
Insert Pushgateway logs relevant to the issue here.
```
